/* 
 * File:   main.cpp
 * Author: Valentinno Cruz
 * Created on September 17, 2018, 12:45 pM
 * Purpose:  Gaddis chap 3 question 2
 */

//System Libraries
#include <iostream>
#include <cmath>
#include <iomanip>
using namespace std;

//User Libraries

//Global Constants - Math/Physics Constants, Conversions,
//                   2-D Array Dimensions

//Function Prototypes

//Execution Begins Here
int main(int argc, char** argv) {
    //Declare Variables
    int classA, classB, classC;//types of seat sections
    int totlTix; //total of all tickets
    int costA, costB, costC; //the cost per seat section
    double revgen; // revenue generated 
  
    
    //Initialize Variables
   
   
    
    //Process/Map inputs to outputs
    cout<<"How many tickets of Class A were sold?  "<<endl;
    cin>>classA;
    cout<<"How many tickets of Class B were sold?  "<<endl;
    cin>>classB;
    cout<<"How many tickets of Class C were sold?  "<<endl;
    cin>>classC;
    

    //Output data
    costA = classA*15; //revenue generated by class A
    costB = classB*12; //revenue generated by class B
    costC = classC*9; //revenue generated by class C
    totlTix = costA+costB+costC;
    revgen = static_cast<double> (totlTix);
    cout<< setprecision (2)<<fixed; //set decimal place by 2
    cout<<"The Total income from ticket sales was $"<<revgen<<endl;
    //Exit stage right!
    return 0;
}